<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;
use RuntimeException;

class CreateDliEduVentureTables extends Migration
{
    private string $schema;

    public function up()
    {
        $this->schema = (string) env('DB_SCHEMA', 'dlieduventure');
        if (! preg_match('/^[a-z_][a-z0-9_]*$/', $this->schema)) {
            throw new RuntimeException('The PostgreSQL schema name is invalid.');
        }

        $schema = '"' . $this->schema . '"';
        $this->db->query('CREATE SCHEMA IF NOT EXISTS ' . $schema);
        $this->db->query('SET search_path TO ' . $schema . ', public');

        $definitions = [
            'event_join' => '("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "member" VARCHAR(100) NOT NULL, "id_event" VARCHAR(100) NOT NULL, "judul_event" TEXT NOT NULL, "jadwal_tgl" TEXT NOT NULL, "jadwal_time" TEXT NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP)',
            'tbl_admin' => '("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR(100) NOT NULL, "email" VARCHAR(100) NOT NULL UNIQUE, "password" VARCHAR(255) NOT NULL, "usertype" INTEGER NOT NULL DEFAULT 1)',
            'tbl_blog' => '("id_blog" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "judul_blog" VARCHAR(100) NOT NULL, "slug_blog" VARCHAR(100) NOT NULL, "isi" TEXT NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "uploader" INTEGER NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updater" INTEGER NOT NULL, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
            'tbl_event' => '("id_event" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "judul_event" VARCHAR(100) NOT NULL, "slug_event" VARCHAR(100) NOT NULL, "isi" TEXT NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "jadwal_tgl" DATE NOT NULL, "jadwal_time" TIME WITHOUT TIME ZONE NOT NULL, "uploader" INTEGER NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updater" INTEGER NOT NULL, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
            'tbl_gallery' => '("id_gallery" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "judul_gallery" VARCHAR(100) NOT NULL, "slug_gallery" VARCHAR(100) NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "uploader" INTEGER NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updater" INTEGER NOT NULL, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
            'tbl_news' => '("id_news" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "judul_news" VARCHAR(100) NOT NULL, "slug_news" VARCHAR(100) NOT NULL, "isi" TEXT NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "uploader" INTEGER NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updater" INTEGER NOT NULL, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
            'tbl_program' => '("id_program" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "judul_program" VARCHAR(100) NOT NULL, "slug_program" VARCHAR(100) NOT NULL, "isi" TEXT NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "uploader" INTEGER NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updater" INTEGER NOT NULL, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
            'tbl_startup' => '("id_startup" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "judul_startup" VARCHAR(100) NOT NULL, "slug_startup" VARCHAR(100) NOT NULL, "isi" TEXT NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "spesifikasi" TEXT NOT NULL, "keunggulan" TEXT NOT NULL, "pencapaian" TEXT NOT NULL, "kategori" TEXT NOT NULL, "teknologi" TEXT NOT NULL, "web" TEXT NOT NULL, "fb" TEXT NOT NULL, "ig" TEXT NOT NULL, "uploader" INTEGER NOT NULL, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "updater" INTEGER NOT NULL, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
            'users' => '("id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR(100) NOT NULL, "email" VARCHAR(100) NOT NULL UNIQUE, "password" VARCHAR(255) NOT NULL, "foto" TEXT NOT NULL, "foto_type" CHAR(10) NOT NULL, "code" VARCHAR(100) NOT NULL, "active" SMALLINT DEFAULT NULL CHECK ("active" IS NULL OR "active" BETWEEN 0 AND 255), "phone" VARCHAR(30) DEFAULT NULL, "address" TEXT DEFAULT NULL, "bio" TEXT DEFAULT NULL, "reset_password" VARCHAR(100) NOT NULL, "usertype" INTEGER NOT NULL DEFAULT 2, "created" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, "modified" TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL)',
        ];

        foreach ($definitions as $table => $definition) {
            $this->db->query('CREATE TABLE IF NOT EXISTS ' . $schema . '."' . $table . '" ' . $definition);
        }

        $indexes = [
            'tbl_blog' => 'slug_blog',
            'tbl_event' => 'slug_event',
            'tbl_gallery' => 'slug_gallery',
            'tbl_news' => 'slug_news',
            'tbl_program' => 'slug_program',
            'tbl_startup' => 'slug_startup',
        ];
        foreach ($indexes as $table => $column) {
            $index = 'idx_' . $table . '_' . $column;
            $this->db->query(
                'CREATE INDEX IF NOT EXISTS "' . $index . '" ON ' . $schema . '."' . $table
                . '" ("' . $column . '")'
            );
        }
        $this->db->query(
            'CREATE INDEX IF NOT EXISTS "idx_event_join_member_event" ON ' . $schema
            . '."event_join" ("member", "id_event")'
        );
        $this->db->query(
            'CREATE INDEX IF NOT EXISTS "idx_tbl_event_schedule" ON ' . $schema
            . '."tbl_event" ("jadwal_tgl", "jadwal_time")'
        );

        $this->db->query(
            'CREATE OR REPLACE FUNCTION ' . $schema . '."update_modified_at"() '
            . 'RETURNS TRIGGER LANGUAGE plpgsql AS $$ '
            . 'BEGIN NEW."modified" = CURRENT_TIMESTAMP; RETURN NEW; END; $$'
        );

        foreach (['tbl_blog', 'tbl_event', 'tbl_gallery', 'tbl_news', 'tbl_startup', 'users'] as $table) {
            $qualifiedTable = $schema . '."' . $table . '"';
            $this->db->query('DROP TRIGGER IF EXISTS "set_modified_at" ON ' . $qualifiedTable);
            $this->db->query(
                'CREATE TRIGGER "set_modified_at" BEFORE UPDATE ON ' . $qualifiedTable
                . ' FOR EACH ROW EXECUTE FUNCTION ' . $schema . '."update_modified_at"()'
            );
        }
    }

    public function down()
    {
        throw new RuntimeException(
            'This migration is intentionally irreversible; back up the PostgreSQL schema before manual removal.'
        );
    }
}
